name: taxi_driver
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fl_country_code_picker:
  flutter_otp_text_field: ^1.1.1
  otp_timer_button: ^1.1.0
  flutter_osm_plugin: ^0.70.0
  flutter_timer_countdown: ^1.0.7
  flutter_rating_bar: ^4.0.1
  fl_chart:
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  cached_network_image: ^3.3.0
  flutter_timezone: ^1.0.8
  http: ^1.1.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  image_picker: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/font/NunitoSans-Regular.ttf
        - asset: assets/font/NunitoSans-Medium.ttf
          weight: 500
        - asset: assets/font/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: assets/font/NunitoSans-Bold.ttf
          weight: 700
        - asset: assets/font/NunitoSans-ExtraBold.ttf
          weight: 800
